---

# setup passwordless sudo for the given user (default: current local user)
#
#

- set_fact:
    current_local_user: "{{ lookup('env', 'USER') }}"

- name: install sudo 
  package: name=sudo state=present

- name: enable sudo for root on ALT Linux
  copy:
    dest: "/etc/sudoers.d/root"
    owner: root
    group: root
    mode: 0600
    content: "root ALL=(ALL) NOPASSWD: ALL"
  when:
    - ansible_distribution_file_path == '/etc/altlinux-release'

- name: setup admin access
  include_tasks: admin_account.yml
  loop: "{{ admin_users }}" 
  loop_control:
    loop_var: admin
    label: "{{ admin.name }}"
